
Sys.setlocale("LC_MESSAGES", "en_US.utf8")
library(httr)
set_config(config(ssl_verifypeer = 0L))
#dev.off()
#options(connectionObserver = NULL) # For problems with RSQLite 
#remotes::install_version("RSQLite", "2.2.5")
library(org.Hs.eg.db)
library(tidyverse)
library(Biobase)
library(edgeR)
library(DESeq2)
library(limma)
library(here)
library(clusterProfiler)
library(biomaRt)
library(org.Hs.eg.db)
library(org.Mmu.eg.db)
library(VennDiagram)
library(gplots)
library(annotationTools)
library(clusterProfiler)
library(ReactomePA)
library(DOSE)
library(homologene)
library(reshape2)
library(ggvenn)
library(ggplot2)
library(ggthemes)
library(ggExtra)
library(hrbrthemes)
library(viridis)
library(stringr)
library(devtools)
library(enrichR)
library(STRINGdb)
library(scales)
library(UpSetR)
library(apeglm)
library(nlme)
library(lme4)
library("BiocParallel")
library(GeneNetworkBuilder)
library(fgsea)
library(ggpubr)
library(EDASeq)

### Marts for BiomaRt
#mart = useMart(biomart = "ensembl")#, host ="http://nov2020.archive.ensembl.org")
#sapiens_ensembl <- useMart(biomart = "ensembl", dataset = "hsapiens_gene_ensembl")#, host="http://nov2020.archive.ensembl.org")
#macaque_ensembl <- useMart(biomart = "ensembl", dataset = "mmulatta_gene_ensembl")#, host="http://nov2020.archive.ensembl.org")

#mart = useMart(biomart = "ensembl")#, host ="http://useast.ensembl.org")
sapiens_ensembl <- useMart(biomart = "ensembl", dataset = "hsapiens_gene_ensembl")#, host="http://useast.ensembl.org")
macaque_ensembl <- useMart(biomart = "ensembl", dataset = "mmulatta_gene_ensembl")#, host="http://useast.ensembl.org")

### String DB's
#string_hs <- STRINGdb$new(version="10", species=9606,score_threshold=400)
                           
#string_mm <- STRINGdb$new( version="10", species=9544,score_threshold=400)